[project]
name = "apprentissage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Elie Attali", email = "elattali06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[project.scripts]
apprentissage = "apprentissage:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
